[#12] Split SSH key creation in helper function and script

diff --git a/scripts/add_ssh_key b/scripts/add_ssh_key
--- a/scripts/add_ssh_key
+++ b/scripts/add_ssh_key
@@ -2,42 +2,14 @@
 
 # Creates a new SSH key pair with a configurable file suffix and email address as comment.
 
-source ./colors
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+source "$SCRIPT_DIR/colors"
+source "$SCRIPT_DIR/functions/ssh_key_functions"
 
 # Variables
 unset -v email
 unset -v suffix
-
-#############################################################
-# Creates a new SSH key and outputs the resulting public key.
-# Arguments:
-#   Email address to use as comment for the key.
-#   File suffix for the resulting key files.
-# Outputs:
-#   Writes public key to stdout.
-# Returns:
-#   0 if SSH key pair was created, non-zero on error.
-#############################################################
-add_ssh_key_and_print_public_key() {
-  local email="$1"
-  local suffix="$2"
-  local filename="$HOME/.ssh/id_ed25519$suffix"
-
-  if [[ -f $filename ]]; then
-    error "Target file $filename already exists." >&2
-    exit 1
-  fi
-
-  cd
-  info "Generating SSH key for $email under $filename."
-  ssh-keygen -t ed25519 -C $email -f $filename
-  eval "$(ssh-agent -s)"
-  ssh-add $filename 
-
-  local public_key=$( cat "${filename}.pub" )
-  info "Your public key is:"
-  info "$public_key"
-}
 
 _help()
 {
@@ -53,34 +25,37 @@ _help()
   echo
 }
 
-# === MAIN === 
-while getopts ":he:s:" option; do
-  case $option in
-    h) _help
-       exit;;
-    e) email=$OPTARG;;
-    s) suffix=$OPTARG;;
-   \?) echo "Error: Invalid option"
-       return 1
-       ;;
-  esac
-done
+main() {
+  while getopts ":he:s:" option; do
+    case $option in
+      h) _help
+         exit;;
+      e) email=$OPTARG;;
+      s) suffix=$OPTARG;;
+     \?)  error "Error: Invalid option"
+         return 1
+         ;;
+    esac
+  done
 
-if [[ -z "$email" ]]; then
-  error "Missing required email address. Please provide it using the flag -e." >&2
-  exit 1
-fi
-
-if [[ -z "$suffix" ]]; then
-  info "No suffix provided. Generating SSH key pair with default filename."
-else
-  if [[ "$suffix" == _* ]]; then
-    info "Suffix already starts with underscore. Continue as is."
-  else
-    info "Adding underscore prefix to provided file suffix."
-    suffix="_$suffix"
+  if [[ -z "$email" ]]; then
+    error "Missing required email address. Please provide it using the flag -e." >&2
+    exit 1
   fi
-fi
 
-add_ssh_key_and_print_public_key $email $suffix
+  if [[ -z "$suffix" ]]; then
+    info "No suffix provided. Generating SSH key pair with default filename."
+  else
+    if [[ "$suffix" == _* ]]; then
+      info "Suffix already starts with underscore. Continue as is."
+    else
+      info "Adding underscore prefix to provided file suffix."
+      suffix="_$suffix"
+    fi
+  fi
+
+  add_ssh_key_and_print_public_key $email $suffix
+}
+
+main "$@"
 
